# Database Configuration
server.port=8082


spring.datasource.url=jdbc:mysql://localhost:3306/loantracker
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional (recommended)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect